# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 749)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(660, 650, 101, 31))
        self.start.setObjectName("start")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(640, 210, 191, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 170, 54, 12))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(170, 341, 141, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(3)
        self.spinBox.setSingleStep(1)
        self.spinBox.setObjectName("spinBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(170, 291, 141, 31))
        self.doubleSpinBox.setMinimum(0.01)
        self.doubleSpinBox.setMaximum(0.05)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(660, 11, 121, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 190, 141, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 389, 141, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 439, 141, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 89, 91, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 139, 91, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 101, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 91, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 290, 111, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 91, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 390, 81, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 440, 81, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 490, 71, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 530, 71, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 570, 151, 41))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(30, 49, 81, 31))
        self.label_16.setObjectName("label_16")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 489, 141, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 529, 141, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(170, 580, 141, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(170, 239, 141, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(170, 140, 141, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(170, 90, 161, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(170, 50, 161, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(170, 10, 161, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(520, 10, 111, 41))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(520, 61, 121, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(520, 110, 111, 31))
        self.label_19.setObjectName("label_19")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(110, 652, 121, 31))
        self.generate.setObjectName("generate")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(660, 59, 121, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(660, 111, 111, 31))
        self.spinBox_2.setMinimum(50)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setSingleStep(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(520, 160, 111, 31))
        self.label_20.setObjectName("label_20")
        self.load_file = QtWidgets.QPushButton(self.centralwidget)
        self.load_file.setGeometry(QtCore.QRect(870, 160, 75, 23))
        self.load_file.setObjectName("load_file")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(660, 160, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.output_text = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text.setGeometry(QtCore.QRect(580, 250, 261, 31))
        self.output_text.setObjectName("output_text")
        self.psd = QtWidgets.QLabel(self.centralwidget)
        self.psd.setGeometry(QtCore.QRect(440, 330, 471, 301))
        self.psd.setObjectName("psd")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 290, 201, 31))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "开始反演"))
        self.label_2.setText(_translate("MainWindow", "反演所得中心粒径"))
        self.comboBox.setItemText(0, _translate("MainWindow", "GRNN"))
        self.comboBox.setItemText(1, _translate("MainWindow", "随机森林"))
        self.lineEdit_2.setText(_translate("MainWindow", "14.6"))
        self.lineEdit_3.setText(_translate("MainWindow", "30°"))
        self.lineEdit_4.setText(_translate("MainWindow", "45°"))
        self.label_4.setText(_translate("MainWindow", "球体折射率"))
        self.label_5.setText(_translate("MainWindow", "介质折射率"))
        self.label_6.setText(_translate("MainWindow", "介质粘度系数"))
        self.label_7.setText(_translate("MainWindow", "环境温度(°C)"))
        self.label_8.setText(_translate("MainWindow", "添加的噪声水平"))
        self.label_9.setText(_translate("MainWindow", "噪声样本数量"))
        self.label_10.setText(_translate("MainWindow", "散射角1"))
        self.label_11.setText(_translate("MainWindow", "散射角2"))
        self.label_12.setText(_translate("MainWindow", "散射角3"))
        self.label_13.setText(_translate("MainWindow", "散射角4"))
        self.label_14.setText(_translate("MainWindow", "峰值粒径范围(nm)"))
        self.label_15.setText(_translate("MainWindow", "数据集粒径范围"))
        self.label_16.setText(_translate("MainWindow", "sigma范围"))
        self.lineEdit_5.setText(_translate("MainWindow", "60°"))
        self.lineEdit_6.setText(_translate("MainWindow", "135°"))
        self.lineEdit_7.setText(_translate("MainWindow", "400,900"))
        self.lineEdit_8.setText(_translate("MainWindow", "20"))
        self.lineEdit_9.setText(_translate("MainWindow", "1.476"))
        self.lineEdit_10.setText(_translate("MainWindow", "2.33"))
        self.lineEdit_11.setText(_translate("MainWindow", "0.05,0.30"))
        self.lineEdit_12.setText(_translate("MainWindow", "100,1200"))
        self.label_17.setText(_translate("MainWindow", "机器学习算法"))
        self.label_18.setText(_translate("MainWindow", "平滑因子"))
        self.label_19.setText(_translate("MainWindow", "决策树数量"))
        self.generate.setText(_translate("MainWindow", "产生数据集"))
        self.lineEdit_13.setText(_translate("MainWindow", "0.01"))
        self.label_20.setText(_translate("MainWindow", "导入路径"))
        self.load_file.setText(_translate("MainWindow", "导入"))
        self.lineEdit.setText(_translate("MainWindow", "\"D:\\pycharm\\研究生阶段\\变压器粒径分布毕设\\1.fit"))
        self.psd.setText(_translate("MainWindow", "PSD曲线"))
        self.label.setText(_translate("MainWindow", "反演所得粒径分布曲线"))

